### PR TITLE
Update Parser.hs

### PR DESCRIPTION
**Pull request by Gurkenglas**

### CODE REVIEW

**Comment by cies** [comment]
Thanks a lot, looks very clean and certainly a big improvement!

I'm not sure if I can as easily follow the code, but I like to have an excuse to get more into applicative form, and dot-free is always great :)

:+1:

**Comment by cies** [comment]
Sorry @Gurkenglas , I was to quick to pull it in. The code didn't build with your PR in, I managed to fix some of the compile errors, until the last two that I had no clue on how to fix.

You you try to have a look at it your self and make a new PR? Thanks.

**Comment by cies** [comment]
@Gurkenglas ping. Could you have a look at this and let me know what you think?

**Comment by Gurkenglas** [comment]
(Huh, I should check that email address more often.)

Can you show me those compile errors? Ideally with a link to that code snippet on that commit!

**Pull request merged**
